default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
  socket: /tmp/mysql.sock
  host: localhost

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: SleepApp_development
  pool: 5
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
  host: localhost

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Sleep_App_test
  pool: 5
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
  host: localhost
